travis:
  secure:
    BINSTAR_TOKEN: DiUqHz5oe9jbRWW77m6BFsDe/o2Bl48PW1dq0W/j+MOPpVzd6soqTolQchyiv4TxqiJpR+D2FJzrijb1s8BkA9pDjjSaWOzKGBZm81beY2KNWz/itlDtq72W9F8XKtCDyz3QX3jDoV30mHmNxX1RqpFI+SIpIZyXjqEKSfIVAqHziNUJd1f5ub/zJntHTTX/iVRTJDKGuQVzpA54H8dBOtzKGFfEGY/p+8xwsO0WcWgliPePz1bLIdbrb/JXHy6OVfRVZQD9jSvUqms9kIsoxCcbm7NBTNL8ZxDolnYIZVskX5qHxiJfLaL+BlDJvQLuHAfK1pFZe2b1xz1odXZHUp+htUo6oU7nkG/ZVbNUdbvZF0QHOzqdK2g9obMaHmGQIUHq3hCbFxgJPvwT59o17ec6+5RFuXjs9HbZkIaTjg1qFa+0NYlgh5YWZCG/CoEDy3QdG89KccW/KPVdmV9KYTgbxBLreOzY5N9nAXwWjdijH4hhrQk2kUtoJjcDEoih8+euXDP2W8Nxqu6CbqX+dUVoD1mMZy7VarUtR9qfNbNbJqOG2EI6BKdMNzzhoU07OS9uBTSK6MPddqsvA79NYEp7HC57GCblUhQWFyrdEL+WSX1i0L+0bHr1uf6PMsGcl3GgHAZ5qfFomr/Wqm4dhy2T8ckz2typYa5pA7JZkSY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
