travis:
  secure:
    BINSTAR_TOKEN: X3546tKGOehku6fHXh1wlO/Ofyd4Ax598SfKLCcMCopBMlK4QtKNvmBLj71dfkca2/p+JUik7SccU6gqGxlwtajOppNv/2V37s4VQgFq6aJBoxC2rYZjmdzp1U1P5jfcinaPiJcPAFt6smSfcFooHFARLEfb0/dHS4eS8y8a+bMNXlpx60BozXhSP3z6883y3wkxNv0blSSjZRyK9vulA8Qtr8ss1qOP+8AEg+76MABdskBebWT0zC68NZSgCSkwQMO06PBRHsBxpD9BkHCs9sSbRSOld7OcaA0iL9p+4g8MYmpsSt2fECoCT0cV8Ar/TlwqjHEAeJENxZISYMSYx9HX2tE3EtcIx5kOUJQw5jjsPxBRWcXe+eDIkyvut+gL/iY1WZXTIUVM5hv1rS7y5FoU+AX4CB6TCzuYv7vx/mgbReUNTY25jh4jIHfB/57uzESCzye1qVudYYdFXsawHlUx7TpZsVY5wGmodtZBk1ObRTJHJKbBlDhjiaKSSGNXdDjwvGXpeIH3GBAuBh215uiQNCAn7eKzPUruix4uX0v3W/cbljDj16+bpf4TeQ7DfBZBHLMAGxCVVyeJA4UZet3bHPJLHD5nE6qhk0TVrOQlGwJ16DqNDn/OcLN6/hrw09xJ7zgPODiCyNKgXJ3naQNh6rmRAzrD6p5pjgGOdC0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
